id = "todo-txt-actions"
name = "Todo.txt Actions"
version = "0.0.1"
schema_version = 1
authors = ["khotyn"]
description = "Syntax highlighting and task actions for todo.txt, done.txt, and .todotxt files."
repository = "https://github.com/khotyn/zed-todotxt"

[language_servers.todotxt-lsp]
name = "Todo.txt LSP"
languages = ["Todo.txt"]
language_ids = { "Todo.txt" = "todotxt" }

[grammars.todotxt]
repository = "https://github.com/khotyn/tree-sitter-todotxt"
rev = "546d16605b30c741f99df5428a1f272d1b54cc7d"
