/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 19
#define LARGE_STATE_COUNT 11
#define SYMBOL_COUNT 18
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_completed_marker = 1,
  sym_priority = 2,
  aux_sym_completion_date_token1 = 3,
  sym_project = 4,
  sym_context = 5,
  sym_metadata = 6,
  sym_text = 7,
  sym__newline = 8,
  sym_source_file = 9,
  sym_task = 10,
  sym_completed_task_prefix = 11,
  sym_active_task_prefix = 12,
  sym__field = 13,
  sym_completion_date = 14,
  sym_creation_date = 15,
  aux_sym_source_file_repeat1 = 16,
  aux_sym_task_repeat1 = 17,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_completed_marker] = "completed_marker",
  [sym_priority] = "priority",
  [aux_sym_completion_date_token1] = "completion_date_token1",
  [sym_project] = "project",
  [sym_context] = "context",
  [sym_metadata] = "metadata",
  [sym_text] = "text",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym_task] = "task",
  [sym_completed_task_prefix] = "completed_task_prefix",
  [sym_active_task_prefix] = "active_task_prefix",
  [sym__field] = "_field",
  [sym_completion_date] = "completion_date",
  [sym_creation_date] = "creation_date",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_task_repeat1] = "task_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_completed_marker] = sym_completed_marker,
  [sym_priority] = sym_priority,
  [aux_sym_completion_date_token1] = aux_sym_completion_date_token1,
  [sym_project] = sym_project,
  [sym_context] = sym_context,
  [sym_metadata] = sym_metadata,
  [sym_text] = sym_text,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym_task] = sym_task,
  [sym_completed_task_prefix] = sym_completed_task_prefix,
  [sym_active_task_prefix] = sym_active_task_prefix,
  [sym__field] = sym__field,
  [sym_completion_date] = sym_completion_date,
  [sym_creation_date] = sym_creation_date,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_task_repeat1] = aux_sym_task_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_completed_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_priority] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_completion_date_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_project] = {
    .visible = true,
    .named = true,
  },
  [sym_context] = {
    .visible = true,
    .named = true,
  },
  [sym_metadata] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_task] = {
    .visible = true,
    .named = true,
  },
  [sym_completed_task_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_active_task_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym__field] = {
    .visible = false,
    .named = true,
  },
  [sym_completion_date] = {
    .visible = true,
    .named = true,
  },
  [sym_creation_date] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_task_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '\n') ADVANCE(29);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '(') ADVANCE(26);
      if (lookahead == '+') ADVANCE(17);
      if (lookahead == ':') ADVANCE(28);
      if (lookahead == '@') ADVANCE(18);
      if (lookahead == 'x') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(27);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(29);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_completed_marker);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_priority);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(aux_sym_completion_date_token1);
      if (lookahead == ':') ADVANCE(16);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(27);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_project);
      if (lookahead == ':') ADVANCE(7);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_project);
      if (lookahead == ':') ADVANCE(8);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_project);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_context);
      if (lookahead == ':') ADVANCE(10);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_context);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_context);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_metadata);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ':') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ')') ADVANCE(4);
      if (lookahead == ':') ADVANCE(16);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(27);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '-') ADVANCE(22);
      if (lookahead == ':') ADVANCE(16);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(27);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '-') ADVANCE(25);
      if (lookahead == ':') ADVANCE(16);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(27);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(28);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(12);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(7);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(6);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(10);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(9);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(27);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(27);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(27);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(27);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(27);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(27);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(13);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(16);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_completed_marker] = ACTIONS(1),
    [sym_priority] = ACTIONS(1),
    [aux_sym_completion_date_token1] = ACTIONS(1),
    [sym_project] = ACTIONS(1),
    [sym_context] = ACTIONS(1),
    [sym_metadata] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(18),
    [sym_task] = STATE(2),
    [sym_completed_task_prefix] = STATE(4),
    [sym_active_task_prefix] = STATE(4),
    [sym__field] = STATE(5),
    [sym_creation_date] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_task_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_completed_marker] = ACTIONS(5),
    [sym_priority] = ACTIONS(7),
    [aux_sym_completion_date_token1] = ACTIONS(9),
    [sym_project] = ACTIONS(11),
    [sym_context] = ACTIONS(11),
    [sym_metadata] = ACTIONS(13),
    [sym_text] = ACTIONS(13),
    [sym__newline] = ACTIONS(15),
  },
  [STATE(2)] = {
    [sym_task] = STATE(3),
    [sym_completed_task_prefix] = STATE(4),
    [sym_active_task_prefix] = STATE(4),
    [sym__field] = STATE(5),
    [sym_creation_date] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_task_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_completed_marker] = ACTIONS(5),
    [sym_priority] = ACTIONS(7),
    [aux_sym_completion_date_token1] = ACTIONS(9),
    [sym_project] = ACTIONS(11),
    [sym_context] = ACTIONS(11),
    [sym_metadata] = ACTIONS(13),
    [sym_text] = ACTIONS(13),
    [sym__newline] = ACTIONS(19),
  },
  [STATE(3)] = {
    [sym_task] = STATE(3),
    [sym_completed_task_prefix] = STATE(4),
    [sym_active_task_prefix] = STATE(4),
    [sym__field] = STATE(5),
    [sym_creation_date] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_task_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_completed_marker] = ACTIONS(23),
    [sym_priority] = ACTIONS(26),
    [aux_sym_completion_date_token1] = ACTIONS(29),
    [sym_project] = ACTIONS(32),
    [sym_context] = ACTIONS(32),
    [sym_metadata] = ACTIONS(35),
    [sym_text] = ACTIONS(35),
    [sym__newline] = ACTIONS(38),
  },
  [STATE(4)] = {
    [sym__field] = STATE(6),
    [aux_sym_task_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(41),
    [sym_completed_marker] = ACTIONS(41),
    [sym_priority] = ACTIONS(41),
    [aux_sym_completion_date_token1] = ACTIONS(43),
    [sym_project] = ACTIONS(45),
    [sym_context] = ACTIONS(45),
    [sym_metadata] = ACTIONS(47),
    [sym_text] = ACTIONS(47),
    [sym__newline] = ACTIONS(49),
  },
  [STATE(5)] = {
    [sym__field] = STATE(7),
    [aux_sym_task_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(41),
    [sym_completed_marker] = ACTIONS(41),
    [sym_priority] = ACTIONS(41),
    [aux_sym_completion_date_token1] = ACTIONS(43),
    [sym_project] = ACTIONS(51),
    [sym_context] = ACTIONS(51),
    [sym_metadata] = ACTIONS(53),
    [sym_text] = ACTIONS(53),
    [sym__newline] = ACTIONS(49),
  },
  [STATE(6)] = {
    [sym__field] = STATE(7),
    [aux_sym_task_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(55),
    [sym_completed_marker] = ACTIONS(55),
    [sym_priority] = ACTIONS(55),
    [aux_sym_completion_date_token1] = ACTIONS(57),
    [sym_project] = ACTIONS(51),
    [sym_context] = ACTIONS(51),
    [sym_metadata] = ACTIONS(53),
    [sym_text] = ACTIONS(53),
    [sym__newline] = ACTIONS(59),
  },
  [STATE(7)] = {
    [sym__field] = STATE(7),
    [aux_sym_task_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(61),
    [sym_completed_marker] = ACTIONS(61),
    [sym_priority] = ACTIONS(61),
    [aux_sym_completion_date_token1] = ACTIONS(63),
    [sym_project] = ACTIONS(65),
    [sym_context] = ACTIONS(65),
    [sym_metadata] = ACTIONS(68),
    [sym_text] = ACTIONS(68),
    [sym__newline] = ACTIONS(61),
  },
  [STATE(8)] = {
    [sym_completion_date] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(71),
    [sym_completed_marker] = ACTIONS(71),
    [sym_priority] = ACTIONS(71),
    [aux_sym_completion_date_token1] = ACTIONS(73),
    [sym_project] = ACTIONS(71),
    [sym_context] = ACTIONS(71),
    [sym_metadata] = ACTIONS(75),
    [sym_text] = ACTIONS(75),
    [sym__newline] = ACTIONS(71),
  },
  [STATE(9)] = {
    [sym_creation_date] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(77),
    [sym_completed_marker] = ACTIONS(77),
    [sym_priority] = ACTIONS(77),
    [aux_sym_completion_date_token1] = ACTIONS(9),
    [sym_project] = ACTIONS(77),
    [sym_context] = ACTIONS(77),
    [sym_metadata] = ACTIONS(79),
    [sym_text] = ACTIONS(79),
    [sym__newline] = ACTIONS(77),
  },
  [STATE(10)] = {
    [sym_creation_date] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(81),
    [sym_completed_marker] = ACTIONS(81),
    [sym_priority] = ACTIONS(81),
    [aux_sym_completion_date_token1] = ACTIONS(9),
    [sym_project] = ACTIONS(81),
    [sym_context] = ACTIONS(81),
    [sym_metadata] = ACTIONS(83),
    [sym_text] = ACTIONS(83),
    [sym__newline] = ACTIONS(81),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(87), 3,
      aux_sym_completion_date_token1,
      sym_metadata,
      sym_text,
    ACTIONS(85), 6,
      ts_builtin_sym_end,
      sym_completed_marker,
      sym_priority,
      sym_project,
      sym_context,
      sym__newline,
  [14] = 2,
    ACTIONS(79), 3,
      aux_sym_completion_date_token1,
      sym_metadata,
      sym_text,
    ACTIONS(77), 6,
      ts_builtin_sym_end,
      sym_completed_marker,
      sym_priority,
      sym_project,
      sym_context,
      sym__newline,
  [28] = 2,
    ACTIONS(91), 3,
      aux_sym_completion_date_token1,
      sym_metadata,
      sym_text,
    ACTIONS(89), 6,
      ts_builtin_sym_end,
      sym_completed_marker,
      sym_priority,
      sym_project,
      sym_context,
      sym__newline,
  [42] = 2,
    ACTIONS(95), 3,
      aux_sym_completion_date_token1,
      sym_metadata,
      sym_text,
    ACTIONS(93), 6,
      ts_builtin_sym_end,
      sym_completed_marker,
      sym_priority,
      sym_project,
      sym_context,
      sym__newline,
  [56] = 2,
    ACTIONS(57), 3,
      aux_sym_completion_date_token1,
      sym_metadata,
      sym_text,
    ACTIONS(55), 6,
      ts_builtin_sym_end,
      sym_completed_marker,
      sym_priority,
      sym_project,
      sym_context,
      sym__newline,
  [70] = 2,
    ACTIONS(99), 3,
      aux_sym_completion_date_token1,
      sym_metadata,
      sym_text,
    ACTIONS(97), 6,
      ts_builtin_sym_end,
      sym_completed_marker,
      sym_priority,
      sym_project,
      sym_context,
      sym__newline,
  [84] = 2,
    ACTIONS(103), 3,
      aux_sym_completion_date_token1,
      sym_metadata,
      sym_text,
    ACTIONS(101), 6,
      ts_builtin_sym_end,
      sym_completed_marker,
      sym_priority,
      sym_project,
      sym_context,
      sym__newline,
  [98] = 1,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(11)] = 0,
  [SMALL_STATE(12)] = 14,
  [SMALL_STATE(13)] = 28,
  [SMALL_STATE(14)] = 42,
  [SMALL_STATE(15)] = 56,
  [SMALL_STATE(16)] = 70,
  [SMALL_STATE(17)] = 84,
  [SMALL_STATE(18)] = 98,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_task_repeat1, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_task_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_task_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_task_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_completed_task_prefix, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_completed_task_prefix, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_active_task_prefix, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_active_task_prefix, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_completed_task_prefix, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_completed_task_prefix, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_creation_date, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_creation_date, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_completion_date, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_completion_date, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_active_task_prefix, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_active_task_prefix, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_completed_task_prefix, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_completed_task_prefix, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_task, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_todotxt(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "todotxt",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
